<<<<<<< HEAD
version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  news-fetcher:
    build: ./news-fetcher-service
    ports:
      - "8081:8081"
    depends_on:
      - redis

  summary-generator:
    build: ./summary-generator-service
    ports:
      - "8082:8082"
    depends_on:
      - redis

  category-classifier:
    build: ./category-classifier-service
    ports:
      - "8083:8083"
    depends_on:
      - redis

  auth-user:
    build: ./auth-user-service
    ports:
      - "8084:8084"
    depends_on:
      - redis
=======
version: "3.8"

services:
  # Database for the User Microservice
  user-db:
    image: postgres:14-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: your_strong_password
    ports:
      - "5432:5432" # Exposes port for local access (optional)
    volumes:
      - user-db-data:/var/lib/postgresql/data

  # Database for the Salon Microservice
  salon-db:
    image: postgres:14-alpine
    container_name: salon-db
    environment:
      POSTGRES_DB: salon_db
      POSTGRES_USER: salon
      POSTGRES_PASSWORD: your_strong_password
    ports:
      - "5433:5432" # Exposes on a different port to avoid conflict
    volumes:
      - salon-db-data:/var/lib/postgresql/data
 
volumes:
  user-db-data:
  salon-db-data:
>>>>>>> 789324764d980133d61ea0977f5188cecf028ae6
