version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"



  user-service:
    build: ./user-service
    ports:
      - "8081:8081"


  resume-parser-service:
    build: ./resume-parser-service
    ports:
      - "8082:8082"


  career-service:
    build: ./career-service
    ports:
      - "8083:8083"


  ai-advisor-service:
    build: ./ai-advisor-service
    ports:
      - "8084:8084"
    depends_on:
      - redis

  notification-service:
    build: ./notification-service
    ports:
      - "8085:8085"
    depends_on:
      - redis

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - resume-parser-service
      - career-service
      - ai-advisor-service
      - notification-service
