version: '3.8'

services:
  # PostgreSQL Service
  postgres-db:
    image: postgres:16-alpine
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  auth-postgres-db:
    image: postgres:16-alpine
    container_name: auth-postgres-container
    environment:
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: auth123
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # MongoDB Service
  mongo-db:
    image: mongo:latest
    container_name: my-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # Recommendation MongoDB Service
  recommendation-mongo-db:
    image: mongo:latest
    container_name: recommendation-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27018:27017"
    volumes:
      - recommendation_mongo_data:/data/db
    restart: unless-stopped

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  recommendation_mongo_data:
  auth_postgres_data:
