spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://root:admin123@localhost:27017/?authSource=admin
      database: activity_db
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: activity-exchange
  queue:
    name: activity-queue
  routing:
    key: activity.tracking
