server:
  port: 8083


spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://root:admin123@localhost:27018/?authSource=admin
      database : ai_db
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



rabbitmq:
  exchange:
    name: activity-exchange
  queue:
    name: activity-queue
  routing:
    key: activity.tracking


gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
    key: AIzaSyBAsNIXsvjhkxLskdJXlBgT_HS9IIcb1ik
  model:
    name: gemini-1.5-flash
  temperature: 0.7
  maxTokens: 1024
